# Generated by Django 6.0.8 on 2026-08-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload a custom photo for your household avatar profile card.', null=True, upload_to='profile_pics/'),
        ),
    ]
