apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: groceries-argoapp
    namespace: argocd
spec:
    destination:
        namespace: grosns
        server: https://kmaz:6443
    source:
        repoURL: git@github.com:ak1922/groceries_tracker.git
        path: k8s/
        targetRevision: HEAD
    project: default
    syncPolicy:
        automated:
            selfHeal: true
            prune: true
