apiVersion: v1
kind: ConfigMap
metadata:
    name: groceries-django-config
    namespace: grosns
data:
    DEBUG: "False"
    DB_HOST: "groceries-postgres-internal"
    DB_PORT: "5432"
    DB_NAME: "groceries_db"
    CELERY_BROKER_URL: "redis://groceries-redis-service:6379/0"
    CELERY_RESULT_BACKEND: "redis://groceries-redis-service:6379/0"