apiVersion: apps/v1
kind: Deployment
metadata:
    name: groceries-postgres-db
    namespace: grosns
    labels:
        app: groceries-postgres
spec:
    replicas: 1
    selector:
        matchLabels:
            app: groceries-postgres
    template:
        metadata:
            labels:
                app: groceries-postgres
        spec:
            nodeSelector:
                kubernetes.io/hostname: kwc4.barocay.com
            containers:
                -   name: gros-psql-container
                    image: postgres:17.2
                    ports:
                       -    containerPort: 5432
                            protocol: TCP
                    env:
                        -   name: POSTGRES_USER
                            valueFrom:
                                secretKeyRef:
                                    name: groceries-postgres-secret
                                    key: POSTGRES_USER
                        -   name: POSTGRES_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: groceries-postgres-secret
                                    key: POSTGRES_PASSWORD
                    volumeMounts:
                        -   mountPath: /var/lib/postgresql/data
                            name: postgres-storage
                        -   mountPath: /docker-entrypoint-initdb.d
                            name: init-script-volume
            volumes:
                -   name: postgres-storage
                    persistentVolumeClaim:
                        claimName: groceries-postgres-pvc
                -   name: init-script-volume
                    configMap:
                        name: groceries-postgres-config
