apiVersion: v1
kind: Secret
metadata:
    name: groceries-postgres-secret
    namespace: grosns
type: Opaque
stringData:
    DJANGO_SECRET_KEY: "django-development-only-key-12345"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"


---
apiVersion: v1
kind: ConfigMap
metadata:
    name: groceries-postgres-config
    namespace: grosns
data:
    postgres-url: "groceries-postgres-internal"
    create_database.sql: |
        CREATE DATABASE groceries_db WITH OWNER postgres ENCODING 'UTF8' LC_COLLATE 'en_US.utf8' LC_CTYPE 'en_US.utf8';
