apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-web-app
    namespace: {{ .Values.global.namespace }}
    labels:
        app: {{ .Release.Name }}-web
spec:
    replicas: {{ .Values.webapp.replicaCount }}
    selector:
        matchLabels:
            app: {{ .Release.Name }}-web
    template:
        metadata:
            labels:
                app: {{ .Release.Name }}-web
        spec:
            nodeSelector:
                kubernetes.io/hostname: {{ .Values.node.hostname | quote }}
            initContainers:
                -   name: database-migration-job
                    image: {{ .Values.webapp.image | quote }}
                    command: ["python", "manage.py", "migrate", "--noinput"]
                    envFrom:
                        -   configMapRef:
                                name: {{ .Release.Name }}-django-config
                    env:
                        -   name: POSTGRES_USER
                            valueFrom:
                                secretKeyRef:
                                    key: POSTGRES_USER
                                    name: {{ .Release.Name }}-postgres-secret
                        -   name: POSTGRES_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    key: POSTGRES_PASSWORD
                                    name: {{ .Release.Name }}-postgres-secret
            containers:
                -   name: groceries-web-container
                    image: "{{ .Values.webapp.image }}"
                    command:
                        -   "sh"
                        -   "-c"
                        -   |
                            python manage.py migrate --noinput && \
                            python manage.py setup_site && \
                            python manage.py setup_admin && \
                            gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --threads 4 --timeout 60 --keep-alive 5
                    ports:
                        -   containerPort: {{ .Values.webapp.containerPort }}
                    envFrom:
                        -   configMapRef:
                                name: {{ .Release.Name }}-django-config
                    env:
                        -   name: POSTGRES_USER
                            valueFrom:
                                secretKeyRef:
                                    key: POSTGRES_USER
                                    name: {{ .Release.Name }}-postgres-secret
                        -   name: POSTGRES_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    key: POSTGRES_PASSWORD
                                    name: {{ .Release.Name }}-postgres-secret
                        -   name: DJANGO_ALLOWED_HOSTS
                            value: {{ .Values.webapp.djangoAllowedHostsEnv | quote }}


---
apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-webapp-service
    namespace: {{ .Values.global.namespace }}
spec:
    selector:
        app: {{ .Release.Name }}-web
    type: NodePort
    externalTrafficPolicy: Local
    ports:
        -   port: {{ .Values.webapp.containerPort }}
            protocol: TCP
            targetPort: {{ .Values.webapp.containerPort }}
            nodePort: {{ .Values.webapp.nodePort }}
