apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-postgres-db
    namespace: {{ .Values.global.namespace }}
    labels:
        app: {{ .Release.Name }}-postgres
spec:
    replicas: {{ .Values.postgres.replicaCount }}
    selector:
        matchLabels:
            app: {{ .Release.Name }}-postgres
    template:
        metadata:
            labels:
                app: {{ .Release.Name }}-postgres
        spec:
            containers:
                -   name: gros-psql-container
                    image: {{ .Values.postgres.image | quote }}
                    ports:
                        -   protocol: TCP
                            containerPort: {{ .Values.postgres.containerPort }}
                    env:
                        -   name: POSTGRES_USER
                            valueFrom:
                                secretKeyRef:
                                    key: POSTGRES_USER
                                    name: {{ .Release.Name }}-postgres-secret
                        -   name: POSTGRES_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    key: POSTGRES_PASSWORD
                                    name: {{ .Release.Name }}-postgres-secret
                    volumeMounts:
                        -   mountPath: /var/lib/postgresql/data
                            name: postgres-storage
                        -   mountPath: /docker-entrypoint-initdb.d
                            name: init-script-volume
            volumes:
                -   name: postgres-storage
                    persistentVolumeClaim:
                        claimName: {{ .Release.Name }}-postgres-pvc
                -   name: init-script-volume
                    configMap:
                        name: {{ .Release.Name }}-postgres-config
