# Internal connecting service for pods and k8s
apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-postgres-internal
    namespace: {{ .Values.global.namespace }}
spec:
    selector:
        app: {{ .Release.Name }}-postgres
    ports:
        -   protocol: TCP
            port: {{ .Values.postgres.containerPort }}
            targetPort: {{ .Values.postgres.containerPort }}


---
# Node port service for site use.
apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-postgres-external
    namespace: {{ .Values.global.namespace }}
spec:
    type: NodePort
    ports:
        -   protocol: TCP
            targetPort: {{ .Values.postgres.containerPort }}
            nodePort: {{ .Values.postgres.nodePort }}
            port: {{ .Values.postgres.containerPort }}
    selector:
        app: {{ .Release.Name }}-postgres


---
# Persistent volume for PostgreSQL

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Release.Name }}-postgres-pvc
    namespace: {{ .Values.global.namespace }}
spec:
    storageClassName: {{ .Values.postgres.storageClassName | quote }}
    accessModes:
        -   ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.postgres.storageSize }}
