apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-postgres-secret
    namespace: {{ .Values.global.namespace }}
type:
    Opaque
stringData:
    DJANGO_SECRET_KEY: {{ .Values.secrets.djangoSecretKey | quote }}
    POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
    POSTGRES_PASSWORD: {{ .Values.secrets.postGresPassword | quote }}
    GMAIL_APP_PASSWORD: {{ .Values.secrets.gmailAppToken | quote }}


---
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-postgres-config
    namespace: {{ .Values.global.namespace }}
data:
    postgres-url: "{{ .Release.Name }}-postgres-internal"
    create_database.sql: |
        CREATE DATABASE groceries_db WITH OWNER postgres ENCODING 'UTF8' LC_COLLATE 'en_US.utf8' LC_CTYPE 'en_US.utf8';
