# Generated by Django 6.0.8 on 2026-08-08 22:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_logged', to=settings.AUTH_USER_MODEL)),
                ('family_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='users.familygroup')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='shopping.store')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('VEG', 'Fruits & Vegetables 🍎'), ('DRY', 'Dairy, Milk & Eggs 🥛'), ('PRO', 'Meat, Poultry & Fish 🥩'), ('BAK', 'Bakery & Bread 🍞'), ('PAN', 'Pantry & Dry Goods 🌾'), ('JNK', 'Snacks & Treats 🍫'), ('BEV', 'Beverages & Drinks 🥤'), ('HSH', 'Household & Cleaning 🧼')], default='PAN', max_length=3)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price per single unit container', max_digits=8)),
                ('unit_type', models.CharField(choices=[('PCS', 'Count / Per Item'), ('LBS', 'Pound (lbs)'), ('OZ', 'Ounce (oz)'), ('GAL', 'Gallon')], default='PCS', max_length=3)),
                ('unit_size', models.DecimalField(decimal_places=2, default=1.0, help_text='e.g., enter 16.00 for a 16oz cereal box', max_digits=6)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppingtrip')),
            ],
        ),
    ]
