# Generated by Django 6.0.8 on 2026-08-09 22:19

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('VEG', 'Fruits & Vegetables 🍎'), ('DRY', 'Dairy, Milk & Eggs 🥛'), ('PRO', 'Meat, Poultry & Fish 🥩'), ('BAK', 'Bakery & Bread 🍞'), ('PAN', 'Pantry & Dry Goods 🌾'), ('JNK', 'Snacks & Treats 🍫'), ('BEV', 'Beverages & Drinks 🥤'), ('HSH', 'Household & Cleaning 🧼')], default='PAN', max_length=3)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per single unit container', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_type', models.CharField(choices=[('PCS', 'Count / Per Item'), ('LBS', 'Pound (lbs)'), ('OZ', 'Ounce (oz)'), ('GAL', 'Gallon')], default='PCS', max_length=3)),
                ('unit_size', models.DecimalField(decimal_places=2, default=1.0, help_text='e.g., enter 16.00 for a 16oz cereal box', max_digits=6)),
                ('brand', models.CharField(blank=True, help_text='e.g., Kirkland, Organic Valley', max_length=100)),
                ('is_essential', models.BooleanField(default=True, help_text='Uncheck for luxury/impulse purchases')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('budget_alert_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Target spending limit for this specific trip', max_digits=10)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('store_type', models.CharField(choices=[('GROCERY', 'Supermarket / Grocery'), ('WHOLESALE', "Wholesale Club (Costco/Sam's)"), ('CONVENIENCE', 'Convenience Store'), ('FARMERS', 'Farmers Market / Local Vendor')], default='GROCERY', max_length=20)),
                ('address', models.CharField(blank=True, help_text='e.g., 123 Main St', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Store specific details (e.g., best place for bulk meat)')),
            ],
        ),
    ]
