# Generated by Django 6.0.8 on 2026-08-09 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingtrip',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_logged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppingtrip',
            name='family_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='users.familygroup'),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppingtrip'),
        ),
        migrations.AddField(
            model_name='shoppingtrip',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='shopping.store'),
        ),
    ]
