global:
    namespace: grosns

# Shared Secret Vault Keys
secrets:
    postgresDb: "groceries_db"
    postgresUser: "postgres"
    postGresPassword: "postgres"
    djangoSecretKey: ""
    gmailAppToken: ""

# Shared System Network Node Parameters
node:
  hostname: "kwc4.barocay.com"

# Web Workloads Parameter Framework
webapp:
    replicaCount: 1
    image: "akwasi14/groceries:latest"
    containerPort: 8000
    nodePort: 30211
    debug: "False"
    allowedHosts: "localhost,127.0.0.1,kwc4.barocay.com,kwc4.barocay.com:30211,groceries-web-app"
    djangoAllowedHostsEnv: "kwc4.barocay.com"
    dbName: "groceries_db"
    dbPort: "5432"

# Celery Worker & Beat
celery:
    worker:
        replicaCount: 1
    beat:
        replicaCount: 1

# Redis database
redis:
    image: redis:7.2-alpine
    imagePullPolicy: IfNotPresent
    port: 6379
    replicaCount: 1

# PostgreSQL database node
postgres:
    replicaCount: 1
    image: "postgres:17.2"
    containerPort: 5432
    storageClassName: "local-path"
    storageSize: 2Gi
    nodePort: 30348

database:
    internalUrl: "groceries-postgres-internal"
